src/Entity/User.php
<?php

namespace App\Entity;

use App\Model\SearchableInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * App\Entity\User.
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Entity\Repository\UserRepository")
 * @Gedmo\Loggable(logEntryClass="App\Entity\LogEntry")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
#[UniqueEntity(fields: ['username'], repositoryMethod: 'findByIncludingSoftDeleted')]
#[UniqueEntity(fields: ['email'], repositoryMethod: 'findByIncludingSoftDeleted')]
class User implements \Serializable, SearchableInterface, UserInterface
{
    final public const DEFAULT_RATE_MULTIPLIER = 1;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected ?int $id = null;

    /**
     * @var string
     * @ORM\Column(name="username", type="string", length=50, unique=true)
     * @Gedmo\Versioned
     */
    #[Assert\NotNull(message: 'Required')]
    protected ?string $username = null;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100, nullable=true)
     * @Gedmo\Versioned
     */
    #[Assert\NotNull(message: 'Required')]
    protected ?string $name = null;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=64)
     * @Gedmo\Versioned
     */
    protected ?string $password = null;

    /**
     * Plain password. Used for model validation. Must not be persisted.
     */
    #[Assert\Length(min: '6')]
    #[Assert\NotBlank(groups: ['NewUser'])]
    protected $plainPassword;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=60, unique=true, nullable=true)
     * @Gedmo\Versioned
     */
    #[Assert\NotNull(message: 'Required')]
    protected ?string $email = null;

    /**
     * @var bool
     *
     * @ORM\Column(name="isActive", type="boolean")
     * @Gedmo\Versioned
     */
    protected ?bool $isActive = true;

    /**
     * @ORM\ManyToMany(targetEntity="Role", inversedBy="users", cascade={"persist", "remove"})
     * @var Collection<Role>
     */
    protected Collection $roles;

    /**
     * @ORM\ManyToMany(targetEntity="Job", mappedBy="engineers", cascade={"persist"})
     * @var Collection<Job>
     */
    protected Collection $jobs;

    /**
     * @ORM\ManyToOne(targetEntity="Customer", inversedBy="users", cascade={"persist"}, )
     */
    protected ?Customer $customer = null;

    /**
     * @ORM\OneToMany(targetEntity="Lead", mappedBy="user", cascade={"persist"})
     * @var Collection<Lead>
     */
    protected Collection $leads;

    /**
     * @ORM\OneToMany(targetEntity="EstimateEvent", mappedBy="user", cascade={"persist"})
     * @var Collection<EstimateEvent>
     */
    protected Collection $estimateEvents;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    protected ?\DateTimeInterface $deletedAt = null;

    /**
     * @ORM\Column(name="password_reset_token", type="string", length=64, nullable=true)
     * @Gedmo\Versioned
     */
    protected ?string $passwordResetToken = null;

    /**
     * @ORM\Column(name="password_reset_token_expiry", type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?\DateTimeInterface $passwordResetTokenExpiry = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\WorkLog", mappedBy="user", cascade={"persist"})
     * @var Collection<WorkLog>
     */
    protected Collection $workLogs;

    /**
     * @ORM\OneToMany(targetEntity="Reminder", mappedBy="user", cascade={"persist"})
     * @var Collection<Reminder>
     */
    protected Collection $reminders;

    /**
     * @ORM\OneToOne(targetEntity="Contact", inversedBy="user", cascade={"persist", "remove"}, )
     */
    protected ?Contact $contact = null;

    /**
     * @ORM\OneToMany(targetEntity="Customer", mappedBy="user", cascade={"persist"})
     * @var Collection<Customer>
     */
    protected Collection $customerAccounts;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Location", mappedBy="engineer", cascade={"persist", "remove"})
     */
    protected ?Location $van = null;

    /**
     * @ORM\Column(name="cost_multiplier", type="decimal", nullable=true, precision=8, scale=2)
     * @Gedmo\Versioned
     */
    #[Assert\GreaterThanOrEqual(value: 0)]
    protected ?float $costMultiplier = 1;

    public function __construct()
    {
        $this->jobs = new ArrayCollection();
        $this->estimateEvents = new ArrayCollection();
        $this->roles            = new ArrayCollection();
        $this->leads            = new ArrayCollection();
        $this->workLogs         = new ArrayCollection();
        $this->reminders        = new ArrayCollection();
        $this->customerAccounts = new ArrayCollection();
    }

    public static function getSearchFields(): array
    {
        return ['id'       => 'ID', 'name'     => 'Name', 'username' => 'Username', 'email'    => 'Email'];
    }

    public static function getSearchCategory(): string
    {
        return 'user';
    }

    public function getDisplayName(): string
    {
        return $this->name . ' (' . $this->username . ')';
    }

    public function addWorkLog($value): User
    {
        $this->workLogs->add($value);

        return $this;
    }

    public function removeWorkLog($value): void
    {
        $this->workLogs->remove($value);
    }

    public function getWorkLogs()
    {
        return $this->worklogs->toArray();
    }

    public function addLead($value): User
    {
        $this->leads->add($value);

        return $this;
    }

    public function removeLead($value): void
    {
        $this->leads->remove($value);
    }

    public function getLeads()
    {
        return $this->leads->toArray();
    }

    public function getSalt(): ?string
    {
        return null;
    }

    // We use bcrypt

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setUsername(?string $value): User
    {
        $this->username = $value;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setName(?string $value): User
    {
        $this->name = $value;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setPassword(?string $value): User
    {
        $this->password = $value;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPlainPassword($value): User
    {
        $this->plainPassword = $value;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setEmail(?string $value): User
    {
        $this->email = $value;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setIsActive(?bool $value): User
    {
        $this->isActive = $value;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function addRole($value): User
    {
        $this->roles->add($value);

        return $this;
    }

    public function removeRole($value): void
    {
        $this->roles->removeElement($value);
    }

    public function addReminder($value): User
    {
        $this->reminders->add($value);

        return $this;
    }

    public function removeReminder($value): void
    {
        $this->reminders->removeElement($value);
    }

    public function getReminders(): Collection
    {
        return $this->reminders;
    }

    public function isAccountNonExpired(): bool
    {
        return true;
    }

    public function isAccountNonLocked(): bool
    {
        return true;
    }

    public function isCredentialsNonExpired(): bool
    {
        return true;
    }

    public function isEnabled(): ?bool
    {
        return $this->isActive;
    }

    public function eraseCredentials(): void
    {
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $value): User
    {
        $this->customer = $value;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getRoles(): array
    {
        return array_map(static fn (Role $role): string => (string) $role, array_merge([new Role('ROLE_USER', 'User')], $this->roles->toArray()));
    }

    /**
     * @return Collection<Role>
     */
    public function getRolesEntity(): Collection
    {
        return $this->roles;
    }

    public function getAssignedRoles(): Collection
    {
        return $this->roles;
    }

    public function setAssignedRoles(Collection $value): void
    {
        $this->roles = $value;
    }

    public function serialize(): ?string
    {
        return serialize([$this->id, $this->username, $this->password, $this->isActive]);
    }

    public function unserialize($serialized): void
    {
        [
            $this->id,
            $this->username,
            $this->password,
            $this->isActive,
        ] = unserialize($serialized);
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): void
    {
        $this->deletedAt = $deletedAt;
    }

    public function getPasswordResetToken(): ?string
    {
        return $this->passwordResetToken;
    }

templates/ServiceParts/list.html.twig
{% extends 'layout.html.twig' %}

{% block search_category %}lead{% endblock %}
{% block page_type %}servicePartsTarget{% endblock %}
{% block title %}Service/Parts Targets{% endblock %}
{% block page_shortcuts %}{% include 'Lead/_shortcuts.html.twig' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-title filter-toggle">
                <span class="pull-left">Service/Parts Targets</span>
                <div class="col-md-3">
                    {% if is_granted('ROLE_SUPER_ADMIN') %}
                        <select class="form-control custom-selector" id="user_selector">
                            <option value="null">Show all leads</option>
                            {% for user in leadOwners %}
                                <option value="{{ user.id }}">{{ user.displayName }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
                <a href="#" class="btn btn-primary pull-right btn-new-item" id="new-item">New</a>
            <div class="clearfix"></div>
            </h1>
            <div class="col-md-5">
                <p>Current Month: Leads In {{ leadsIn }}, Leads contacted {{ leadsPercentage }}% ({{ leadsInWithNoContact }}) </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="waterfall" id="lead-filter">

                {% include 'Lead/_leadFilterPanel.html.twig' with { 'panelNumber': 1, 'panelTitle': 'No contact', 'leads': leads, 'priorities': priorities } %}
                {% include 'Lead/_leadFilterPanel.html.twig' with { 'panelNumber': 2, 'panelTitle': 'Contact made', 'leads': leads, 'priorities': priorities } %}
                {% include 'Lead/_leadFilterPanel.html.twig' with { 'panelNumber': 3, 'panelTitle': 'Action required', 'leads': leads, 'priorities': priorities } %}
                {% include 'Lead/_leadFilterPanel.html.twig' with { 'panelNumber': 5, 'panelTitle': 'Quoting', 'leads': leads, 'priorities': priorities } %}

            </div>
        </div>
    </div>

    <div class="row">
        <div id="lead-particulars"></div>
    </div>

    {% include '_formModal.html.twig' with { modalType: 'lead', modalTitle: 'Service Parts Target Lead', modalNewRoute: path('new_primary_target'), modalEditRoute: path('edit_lead') } %}

<script src="/js/waterfall-navigation.js"></script>
<script type="text/javascript">

$(function(){
    userId = '{{ userId }}'
    if (userId) {
        $('#user_selector option').filter(function() {
            return ($(this).val() == userId);
        }).prop('selected', true);
    };
})

$('.panel-link:first').addClass('selected');
$('.panel-link:first').focus();

$('.panel-item.panel-link').on('click', function() {
    var $ele = $(this);
    $('.panel-item.panel-link').removeClass('active');
    $('.panel-item.panel-link').removeClass('selected');

    $ele.addClass('active');
    $ele.addClass('selected');
    var leadId = $ele.data('id');

    if(leadId) {
        var url = "{{ path('view_lead') }}/" + leadId;
        window.location.href = url;
    }
 });


$('#user_selector').on('change', function(){
    var userId = $('#user_selector').find(':selected').val();

    if (userId == 'null') {
        var url    = "{{ path('list_service_parts_leads') }}";
    } else {
        var url    = "{{ path('list_service_parts_leads') }}/" + userId;
    }

    window.location.href = url;
    return false;
})

</script>
{% endblock %}