src/Entity/Lead.php
<?php

namespace App\Entity;

use App\Model\SearchableInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Table(name="lead")
 * @ORM\Entity(repositoryClass="App\Entity\Repository\LeadRepository")
 * @Gedmo\Loggable(logEntryClass="App\Entity\LogEntry")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class Lead implements SearchableInterface
{
    public $newSource;

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Gedmo\Versioned
     */
    protected ?int $id = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Customer", cascade={"persist"}, inversedBy="leads")
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @Gedmo\Versioned
     */
    protected ?Customer $customer = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"persist"}, inversedBy="leads")
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @Gedmo\Versioned
     */
    protected ?User $user = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Source", cascade={"persist"}, inversedBy="leads")
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @Gedmo\Versioned
     */
    protected ?Source $source = null;

    /**
     * @ORM\Column(name="type", type="string", length=255)
     * @Gedmo\Versioned
     */
    protected ?string $type = 'Not Yet Established';

    /**
     * @ORM\Column(name="status", type="string", length=255)
     * @Gedmo\Versioned
     */
    protected ?string $status = 'No contact';

    /**
     * @ORM\Column(name="value", type="string", length=255, nullable=true)
     * @Gedmo\Versioned
     */
    protected ?string $value = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", cascade={"persist"}, mappedBy="lead")
     * @ORM\OrderBy({"date" = "DESC"})
     * @var Collection<Note>
     */
    protected Collection $notes;

    /**
     * @ORM\Column(name="received_date", type="datetime", nullable=true)
     * @Gedmo\Versioned
     * @Gedmo\Timestampable(on="create")
     */
    protected ?\DateTimeInterface $receivedDate = null;

    /**
     * @ORM\Column(name="initial_contact", type="datetime", nullable=true)
     * @Gedmo\Versioned
     * @Gedmo\Timestampable(on="create")
     */
    protected ?\DateTimeInterface $initialContact = null;

    /**
     * @ORM\Column(name="last_contact", type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?\DateTimeInterface $lastContact = null;

    /**
     * @ORM\Column(name="priority", type="string", length=255)
     * @Gedmo\Versioned
     */
    protected ?string $priority = null;

    /**
     * @ORM\Column(name="future_target", type="boolean")
     * @Gedmo\Versioned
     */
    protected ?bool $futureTarget = false;

    /**
     * @ORM\Column(name="primary_target", type="boolean", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?bool $primaryTarget = false;

    /**
     * @ORM\Column(name="unsuccessful", type="boolean", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?bool $unsuccessful = false;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reminder", mappedBy="lead", cascade={"persist", "remove"})
     * @ORM\OrderBy({"date" = "DESC"})
     * @var Collection<Reminder>
     */
    protected Collection $reminders;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Contact", inversedBy="leads", cascade={"persist"})
     * @ORM\JoinColumn(onDelete="SET NULL")
     * @var Collection<Contact>
     */
    protected Collection $contacts;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?\DateTimeInterface $deletedAt = null;

    /**
     * @ORM\Column(name="completion_stage", type="integer", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?int $completionStage = 1;

    /**
     * @ORM\Column(name="completion_date", type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?\DateTimeInterface $completionDate = null;

    /**
     * @ORM\Column(name="unsuccessful_reason", type="string", length=255, nullable=true)
     * @Gedmo\Versioned
     */
    protected ?string $unsuccessfulReason = null;

    /**
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     * @Gedmo\Versioned
     * @Gedmo\Timestampable(on="update")
     */
    protected ?\DateTimeInterface $updatedAt = null;

    /**
     * @ORM\Column(name="update_count", type="integer")
     * @Gedmo\Versioned
     */
    protected ?int $updateCount = 0;

    /**
     * @ORM\Column(name="is_delivered", type="boolean", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?bool $isDelivered = false;

    /**
     * @ORM\Column(name="delivery_date", type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?\DateTimeInterface $deliveryDate = null;

    /**
     * @ORM\Column(name="contract_renewal_date", type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?\DateTimeInterface $contractRenewalDate = null;

    /**
     * @ORM\Column(name="is_service_parts_lead", type="boolean", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?bool $isServicePartsLead = false;

    /**
     * @ORM\Column(name="visit_me", type="boolean", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?bool $visitMe = false;

    /**
     * @ORM\Column(name="archived_at", type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?\DateTimeInterface $archivedAt = null;

    /**
     * @ORM\Column(name="archived", type="boolean", nullable=true)
     * @Gedmo\Versioned
     */
    protected ?bool $archived = false;

    public function __construct()
    {
        $this->notes           = new ArrayCollection();
        $this->contacts        = new ArrayCollection();
        $this->reminders       = new ArrayCollection();
    }

    public static function getSearchFields(): array
    {
        return ['id'     => 'ID', 'type'   => 'Type', 'status' => 'Status', 'value'  => 'Value'];
    }

    public static function getSearchCategory(): string
    {
        return 'lead';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setCustomer(?Customer $value): Lead
    {
        $this->customer = $value;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setType(?string $value): Lead
    {
        $this->type = $value;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setSource(?Source $value): Lead
    {
        $this->source = $value;

        return $this;
    }

    public function getSource(): ?Source
    {
        return $this->source;
    }

    public function setStatus(?string $value): Lead
    {
        $this->status = $value;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setPriority(?string $value): Lead
    {
        $this->priority = $value;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->priority;
    }

    public function setInitialContact(?\DateTimeInterface $value): Lead
    {
        $this->initialContact = $value;

        return $this;
    }

    public function getInitialContact(): ?\DateTimeInterface
    {
        return $this->initialContact;
    }

    public function setLastContact(?\DateTimeInterface $value): Lead
    {
        $this->lastContact = $value;

        return $this;
    }

    public function getLastContact(): ?\DateTimeInterface
    {
        return $this->lastContact;
    }

    public function setDeletedAt(?\DateTimeInterface $value): Lead
    {
        $this->deletedAt = $value;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setFutureTarget(?bool $value): Lead
    {
        $this->futureTarget = $value;

        return $this;
    }

    public function getFutureTarget(): ?bool
    {
        return $this->futureTarget;
    }

    public function setPrimaryTarget(?bool $value): Lead
    {
        $this->primaryTarget = $value;

        return $this;
    }

    public function getPrimaryTarget(): ?bool
    {
        return $this->primaryTarget;
    }

    public function setCompletionDate(?\DateTimeInterface $value): Lead
    {
        $this->completionDate = $value;

        return $this;
    }

    public function getCompletionDate(): ?\DateTimeInterface
    {
        return $this->completionDate;
    }

    public function setContractRenewalDate(?\DateTimeInterface $value): Lead
    {
        $this->contractRenewalDate = $value;

        return $this;
    }

    public function getContractRenewalDate(): ?\DateTimeInterface
    {
        return $this->contractRenewalDate;
    }

    public function getDescription(): string
    {
        $parts = [];

        if ($this->customer) {
            $parts[] = $this->getCustomer()->getName();
        }
        if ($this->type) {
            $parts[] = $this->getType();
        }

        $this->description = implode(' - ', $parts);

        return $this->description;
    }

    public function addNote($value): Lead
    {
        $this->notes->add($value);
        $value->setLead($this);

        return $this;
    }

    public function removeNote($value): void
    {
        $this->notes->removeElement($value);
    }

    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addContact($value): Lead
    {
        $this->contacts->add($value);

        return $this;
    }

    public function removeContact($value): void
    {

src/Form/Type/AssetType.php
<?php

namespace App\Form\Type;

use App\Entity\Contact;
use App\Entity\Customer;
use App\Model\Warranty;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\OptionsResolver\OptionsResolver;

abstract class AssetType extends AbstractType
{
    public function __construct(protected EntityManagerInterface $em)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $isEdit = $builder->getData()->getId();

        $builder->setMethod(Request::METHOD_POST);
        $builder
            ->add('newMake', TextType::class)
            ->add('newModel', TextType::class)
            ->add('serial', TextType::class)
            ->add('yearOfManufacture', TextType::class)
            ->add('purchasePrice', MoneyType::class, ['currency' => 'GBP'])
            ->add('purchasedDate', DateTimeType::class, ['html5' => false, 'widget' => 'single_text', 'format' => 'yyyy-MM-dd', 'attr' => ['class' => 'datepicker', 'data-date-format' => 'YYYY-MM-DD']])
            ->add('manufacturersWarranty', ChoiceType::class, ['choices' => array_flip(Warranty::CHOICES), 'attr' => ['data-reveal' => '#warranty-duration']])
            ->add('manufacturersWarrantyDuration', IntegerType::class, ['attr' => ['rightAddon' => 'months']])
            ->add('secondLevelManufacturersWarranty', ChoiceType::class, ['choices' => array_flip(Warranty::CHOICES), 'attr' => ['data-reveal' => '#second-warranty-duration']])
            ->add('secondLevelManufacturersWarrantyDuration', IntegerType::class, ['attr' => ['rightAddon' => 'months']])
            ->add('stockValue', MoneyType::class, ['currency' => 'GBP']);

        if (!$isEdit) {
            $builder
                ->add('detail', TextareaType::class, ['mapped' => false])
                ->add('date', DateTimeType::class, ['html5' => false, 'mapped' => false, 'widget' => 'single_text', 'format' => 'yyyy-MM-dd', 'data'   => new \DateTime('now'), 'attr'   => ['class'            => 'datepicker', 'data-date-format' => 'YYYY-MM-DD']]);
        }

        if ($options['showCustomer']) {
            $customerOptions = ['class' => Customer::class, 'choice_label' => 'name', 'mapped' => false, 'query_builder' => fn (EntityRepository $er) => $er->createQueryBuilder('c')
                ->andWhere('c.isActive = true')
                ->orderBy('c.name', 'ASC')];

            $customerRepo    = $this->em->getRepository(Customer::class);
            $defaultCustomer = $customerRepo->getDefaultCustomer();

            if ($defaultCustomer) {
                $customerOptions['preferred_choices'] = [$defaultCustomer];
            } else {
                $customerOptions['placeholder'] = 'None (Asset Register)';
            }

            $builder->add('customer', EntityType::class, $customerOptions)
                ->add('clientFleet', TextType::class, ['mapped' => false, 'attr' => ['placeholder' => 'N/A']]);
        }
        $builder->addEventListener(FormEvents::PRE_SET_DATA, $this->onPreSetDataCustomer(...));
    }

    public function onPostSubmitCustomer(FormEvent $event): void
    {
        $form     = $event->getForm()->getParent();
        $customer = $event->getForm()->getData();

        $this->addContacts($form, $customer);
    }

    public function onPreSetDataCustomer(FormEvent $event): void
    {
        $job = $event->getData();
        $form = $event->getForm();

        $customer = $job->getCustomer();
        $this->addContacts($form, $customer);
    }

    public function addContacts(FormInterface $form, $customer = null): void
    {
        $formOptions = ['class' => Contact::class, 'mapped' => false, 'expanded' => true, 'multiple' => true, 'choice_label' => 'name', 'label' => false];

        if ($customer) {
            $formOptions['query_builder'] = fn (EntityRepository $er) => $er->createQueryBuilder('con')
                ->andWhere('con.customer = :customer')
                ->setParameter('customer', $customer);
        } else {
            $formOptions['query_builder'] = null;
        }

        $form->add('contacts', EntityType::class, $formOptions);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'showCustomer' => false,
        ])->setAllowedTypes('showCustomer', ['bool']);
    }
}

templates/Asset/_newAssetEmail.html.twig
<h3>Hello,</h3>

<h4>A new asset has been created on Fleetmanager:</h4>

<p><strong>Details: </strong>{{ asset.nameString }}</p>
<p><strong>Type: </strong>{{ asset.assetType }}</p>

<p><a href="{{ url('view_asset', { id: asset.id }) }}">Link to Asset on Fleetmanager</a></p>

templates/Asset/_newJobModal.html.twig
<div class="modal" id="new-job-modal" tabindex="-1" role="dialog" aria-labelledby="form-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="new-job-form-modal-label"><span class="form-modal-title">Create job</span></h2>
            </div>
            <div class="modal-body">
                <div class="new-job-form-holder"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var $newJobModal   = $('#new-job-modal');
    var $newJobWrapper = $newJobModal.find('.new-job-form-holder');
    var $newJobFooter  = $newJobModal.find('.modal-footer');
    var reloadPage     = false;

    $('#newJob').on('click',  function(e) {
        e.preventDefault();
        $newJobModal.modal('show');
    });

    $newJobModal.on('hide.bs.modal', function (e) {
        $newJobWrapper.html('');

        if (reloadPage) {
            location.reload(true);
        }

        $newJobModal.find('.modal-form-submit').remove();
    });

    $newJobModal.on('show.bs.modal', function (e) {
        newJobLoadform(e);
    });

    function newJobLoadform(e) {
        $.get('{{ path('new_job', { asset: asset.id }) }}', function(data) {
            if (data.displayForm) {
                $newJobWrapper.html(data.html);
                $newJobModal.find('[autofocus]:first').focus();
                $assignButton = $('<button type="button" data-loading-text="Saving..." class="btn btn-default extra-modal-btn" id="save-assign">Save & Assign</button>');
                $newJobFooter.prepend($assignButton);
                $newJobFooter.prepend('<button type="button" class="btn btn-primary modal-form-submit" data-loading-text="Saving...">Save</button>');
                newJobBindForm();
                $assignButton.on('click', function(e) {
                    e.preventDefault();
                    $input = $('<input type="hidden" name="assign" value="1">');
                    var $form = $('#new-job-modal form');

                    $form.append($input);
                    $form.submit();
                    var $engineerModal   = $('#assign-engineer-modal');
                    $engineerModal.on('show.bs.modal', function (e) {
                        engineerLoadform(e);
                    });

                });
            }
        });
    }

    function newJobBindForm() {
        var $form   = $newJobWrapper.find('form');
        var $button = $newJobFooter.find('.modal-form-submit');
        $form.find('.datepicker').datetimepicker({
            pickTime: false
        });

        $form.find('.datetimepicker').datetimepicker();

        $button.unbind('click');
        $button.click(function() {
            $form.submit();
        });

        $form.ajaxForm({
            dataType: 'json',
            beforeSubmit: function(arr, $form) {
                $button.button('loading');
            },
            success: function(response, statusText, xhr, $form) {
                if (response.displayForm) {
                    $wrapper.html(response.html);
                    $button.button('reset');
                    if ($newJobModal.find('.has-error')) {
                        $newJobModal.find('.has-error input:first').focus();
                    } else {
                        $newJobModal.find('[autofocus]:first').focus();
                    }
                    bindForm();
                } else {
                    if (response.url) {
                        location.href = response.url;
                        return;
                    } else if (response.refresh) {
                        reloadPage = true;
                    }
                    $newJobModal.modal('hide');
                }
            },
            error: function() {
                growlError('There was an error - the job was not saved');
                $newJobModal.modal('hide');
            }
        });

        listenForFormChanges();
    }
</script>

templates/Asset/_newMaintenanceForm.html.twig
{% form_theme form 'Form/form_layout_horizontal.html.twig' %}

<div class="panel-group" id="accordion">
    {{ form_start(form, {'action': formRoute, 'attr': { 'class': 'form-horizontal', novalidate: 'novalidate' } }) }}
        {{ form_errors(form) }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#note_info">New Maintenance Task</a></h4>
            </div>
            <div id="note_info" class="panel-collapse collapse in">
                <div class="panel-body">
                    {{ form_row( form.detail, { 'attr': { 'autofocus': 1 } }) }}
                    {{ form_row( form.amount ) }}
                    {{ form_row( form.date ) }}
                </div>
            </div>
        </div>

        <div class="hidden-form-field">
            {{ form_rest(form) }}
        </div>
    {{ form_end(form) }}
</div>

templates/Asset/_newNoteModal.html.twig
<div class="modal" id="new-note-modal" tabindex="-1" role="dialog" aria-labelledby="form-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="new-note-form-modal-label"><span class="form-modal-title">New Note</span></h2>
            </div>
            <div class="modal-body">
                <div class="new-note-form-holder"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var $newNoteModal   = $('#new-note-modal');
    var $newNoteWrapper = $newNoteModal.find('.new-note-form-holder');
    var $newNoteFooter  = $newNoteModal.find('.modal-footer');

    $('#newNote').on('click',  function(e) {
        $newNoteModal.modal('show');
    });

    $newNoteModal.on('hide.bs.modal', function (e) {
        $newNoteWrapper.html('');

        if (reloadPage) {
            location.reload(true);
        }

        $newNoteModal.find('.modal-form-submit').remove();
    });

    $newNoteModal.on('show.bs.modal', function (e) {
        newNoteLoadform(e);
    });

    function newNoteLoadform(e) {
        $.get('{{ path('new_asset_note', { 'id': asset.id }) }}', function(data) {
            if (data.displayForm) {
                $newNoteWrapper.html(data.html);
                $newNoteModal.find('[autofocus]:first').focus();
                $newNoteFooter.prepend('<button type="button" class="btn btn-primary modal-form-submit" data-loading-text="Saving...">Save</button>');
                newNoteBindform();
            }
        });
    }

    function newNoteBindform() {
        var $newNoteform   = $newNoteWrapper.find('form');
        var $newNoteButton = $newNoteFooter.find('.modal-form-submit');
        $newNoteform.find('.datepicker').datetimepicker({
            pickTime: false
        });

        $newNoteform.find('.datetimepicker').datetimepicker();

        $newNoteButton.unbind('click');
        $newNoteButton.click(function() {
            $newNoteform.submit();
        });

        $newNoteform.ajaxForm({
            dataType: 'json',
            beforeSubmit: function(arr, $newNoteform) {
                $newNoteButton.button('loading');
            },
            success: function(response, statusText, xhr, $newNoteform) {
                if (response.displayForm) {
                    $newNoteWrapper.html(response.html);
                    if ($newNoteModal.find('.has-error')) {
                        $newNoteModal.find('.has-error input:first').focus();
                    } else {
                        $newNoteModal.find('[autofocus]:first').focus();
                    }
                    newNoteBindform();
                } else {
                    if(response.refresh) {
                        reloadPage = true;
                    }
                    $newNoteModal.modal('hide');
                }
            },
            error: function() {
                growlError('There was an error - the note was not assigned to the asset.');
                $newNoteButton.button('reset');
            }
        });

        listenForFormChanges();
    }
</script>

templates/Asset/_particularsMaintenances.html.twig
<div class="row">
    <div class="col-md-12">
        <div class="spacer"></div>
        <div id="maintenance-section" class="information-section col-md-6 col-sm-12">
            <div class="section-header">
                <h2>Maintenance Tasks</h2>
                {% if canEdit %}<a class="btn btn-success btn-xs pull-right" href="#" id="newMaintenanceTask">New</a>{% endif %}
            </div>
            <div class="section-content table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Detail</th>
                            <th>Amount</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for maintenance in lifecyclePeriod.maintenances %}
                            <tr>
                                <td><a href="{{ path('view_maintenance', { 'id': maintenance.id }) }}">{{ maintenance.detail }}</a></td>
                                <td>£{{ maintenance.amount | default ('--') }}</td>
                                <td>{{ maintenance.date ? maintenance.date|date('d/m/Y') : 'No date saved.' }}</td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="4">No stored maintenance tasks.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

templates/Asset/_particularsNotes.html.twig
<div id="notes-section" class="information-section col-md-6 col-sm-12">
    <div id="notes-module_heading" class="section-header">
        <h2>Notes</h2>
        {% if canEdit %}<a class="btn btn-success btn-xs pull-right" href="#" id="newNote">New</a>{% endif %}
    </div>
    <div class="section-content table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Detail</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                {% for note in asset.allNotes %}
                    <tr>
                        <td><a href="{{ path('view_note', { 'id': note.id }) }}">{{ note.detail }}</a></td>
                        <td>{{ note.date ? note.date|date('d/m/Y H:i:s') : 'No date saved.' }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4">No stored notes.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/Asset/_returnForm.html.twig
{% form_theme form 'Form/form_layout_horizontal.html.twig' %}

<div class="panel-group" id="accordion">
    {{ form_start(form, {'action': formRoute, 'attr': { 'class': 'form-horizontal', novalidate: 'novalidate' } }) }}
        {{ form_errors(form) }}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#return-main">Details</a></h4>
            </div>
            <div id="return-main" class="panel-collapse collapse in">
                <div class="panel-body">
                    {{ form_row(form.end) }}

                    {% if form.residualValue is defined %}{{ form_row(form.residualValue) }}{% endif %}
                    {% if form.tradeInValue is defined %}{{ form_row(form.tradeInValue) }}{% endif %}
                </div>
            </div>
        </div>

        {{ form_rest(form) }}
    {{ form_end(form) }}
</div>

templates/Asset/view.html.twig
{% extends 'layout.html.twig' %}

{% set canEdit = is_granted('ROLE_SERVICE_ADMIN') %}

{% block search_category asset.searchCategory %}
{% block page_type asset.searchCategory %}
{% block title %}{{ asset.id }}{% endblock %}
{% block page_shortcuts %}{% if asset.assetType == 'Truck' %}{% include 'Truck/_shortcuts.html.twig' %}{% endif %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-title option-title">
                <h1><span class="icomoon-truck icomoon-inline"></span>{{ asset.nameString }}</h1>
                <div class="pull-right item-actions">
                    {% if canEdit %}
                        <a class="btn btn-primary" href="{{ path('asset_maintenance_report', { 'id': asset.id }) }}">Maintenance Report</a>
                        <a class="btn btn-danger" data-toggle="modal" data-target="#confirm-delete-modal" data-href="{{ path('delete_asset') }}/{{ asset.id }}" href="#">Delete</a>
                    {% endif %}
                </div>
            </div>
            <div class="clearfix"></div>

            <div id="particulars-holder">
                {{ render(controller('App\\Controller\\AssetController::particularsAction', { id: asset.id })) }}
            </div>

        </div>
    </div>

    {% if canEdit %}
        {% include '_formModal.html.twig' with { modalType: asset.assetType, modalNewRoute: path(asset.newRoute), modalEditRoute: path(asset.editRoute, asset.editParams) } %}
    {% endif %}
{% endblock %}